# Step 1: Base image
FROM alpine:latest

# Step 2: Set the working directory to /app
WORKDIR /app

# Step 3: Copy files into the /app directory
COPY example2/ .
# Step 4: Default command to show the files in /app
CMD ["ls", "-l"]
