## DB 접속 방법

도움이 되는 자료

svelte에서는 hook.server.ts → layout.server.ts → page.server.ts  순으로 파일이 실행됩니다.

현재 db 접속은 웹서버가 시작하는 시점이 아니라 처음으로 클라이언트로부터 요청을 받았을때

hook.server.ts에서 db접속하는 함수를 한번 실행해서 연결합니다.

![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/379b64ad-551d-45da-b2fa-34d84c7390fd/fea638cb-2972-4dda-bfee-a004777520c9/image.png)

![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/379b64ad-551d-45da-b2fa-34d84c7390fd/f0621afa-77e9-4f9b-b4ab-026bea67e62c/image.png)

이렇게 접속을하게되면 

dbs에 접속 정보가 담기게되고 콜랙션(모델)들을 import할때 해당 connection에 있는

콜랙션을 가져오게 됩니다.

예시로 pointHistoryModel의 경우 저 함수를 호출하게 되면

![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/379b64ad-551d-45da-b2fa-34d84c7390fd/3eff3f76-a660-4a23-b525-a37938f67471/image.png)

![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/379b64ad-551d-45da-b2fa-34d84c7390fd/08ab2978-8e21-40a7-a596-fffe0fdefac7/image.png)

이렇게 db에 있는 콜랙션을 가져오게 됩니다.

하나의 웹서비스에서 여러 db를 연결해야하는 경우가 있어서 저렇게 작성을 했지만 

시월뮤직의 경우 dbs에는 하나의 커넥션 정보만 담기게되고

index는 항상 0으로 설정하면됩니다.